(function() {var implementors = {};
implementors["slog"] = [];implementors["slog_stream"] = ["impl&lt;W:&nbsp;'static + <a class='trait' href='https://doc.rust-lang.org/nightly/std/io/trait.Write.html' title='std::io::Write'>Write</a> + <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Send.html' title='core::marker::Send'>Send</a>,&nbsp;F:&nbsp;<a class='trait' href='slog_stream/trait.Format.html' title='slog_stream::Format'>Format</a> + <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Send.html' title='core::marker::Send'>Send</a>&gt; <a class='trait' href='slog/trait.Drain.html' title='slog::Drain'>Drain</a> for <a class='struct' href='slog_stream/struct.Streamer.html' title='slog_stream::Streamer'>Streamer</a>&lt;W,&nbsp;F&gt;","impl&lt;F:&nbsp;<a class='trait' href='slog_stream/trait.Format.html' title='slog_stream::Format'>Format</a> + <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Send.html' title='core::marker::Send'>Send</a>&gt; <a class='trait' href='slog/trait.Drain.html' title='slog::Drain'>Drain</a> for <a class='struct' href='slog_stream/struct.AsyncStreamer.html' title='slog_stream::AsyncStreamer'>AsyncStreamer</a>&lt;F&gt;",];implementors["slog_syslog"] = ["impl <a class='trait' href='slog/trait.Drain.html' title='slog::Drain'>Drain</a> for <a class='struct' href='slog_syslog/struct.Streamer3164.html' title='slog_syslog::Streamer3164'>Streamer3164</a>",];implementors["slog_stdlog"] = ["impl <a class='trait' href='slog/trait.Drain.html' title='slog::Drain'>Drain</a> for <a class='struct' href='slog_stdlog/struct.StdLog.html' title='slog_stdlog::StdLog'>StdLog</a>",];implementors["slog_atomic"] = ["impl&lt;E&gt; <a class='trait' href='slog/trait.Drain.html' title='slog::Drain'>Drain</a> for <a class='struct' href='slog_atomic/struct.AtomicSwitch.html' title='slog_atomic::AtomicSwitch'>AtomicSwitch</a>&lt;E&gt;",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
