(function() {var implementors = {};
implementors['ansi_term'] = ["impl&lt;'a&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html' title='core::fmt::Display'>Display</a> for <a class='struct' href='ansi_term/struct.ANSIString.html' title='ansi_term::ANSIString'>ANSIString</a>&lt;'a&gt;","impl&lt;'a&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html' title='core::fmt::Display'>Display</a> for <a class='struct' href='ansi_term/struct.ANSIStrings.html' title='ansi_term::ANSIStrings'>ANSIStrings</a>&lt;'a&gt;",];implementors['libc'] = [];implementors['serde'] = ["impl <a class='trait' href='core/fmt/trait.Display.html' title='core::fmt::Display'>Display</a> for <a class='struct' href='rustc_unicode/char/struct.DecodeUtf16Error.html' title='rustc_unicode::char::DecodeUtf16Error'>DecodeUtf16Error</a>","impl <a class='trait' href='core/fmt/trait.Display.html' title='core::fmt::Display'>Display</a> for <a class='enum' href='serde/de/value/enum.Error.html' title='serde::de::value::Error'>Error</a>",];implementors['serde_json'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html' title='core::fmt::Display'>Display</a> for <a class='enum' href='serde_json/error/enum.Error.html' title='serde_json::error::Error'>Error</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html' title='core::fmt::Display'>Display</a> for <a class='enum' href='serde_json/value/enum.Value.html' title='serde_json::value::Value'>Value</a>",];implementors['slog'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html' title='core::fmt::Display'>Display</a> for <a class='enum' href='slog/enum.Level.html' title='slog::Level'>Level</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
